DROP TABLE Cities
DROP TABLE LoadingStations
DROP TABLE Municipalities
DROP TABLE VehicleRoutes
DROP TABLE Cards
DROP TABLE VehicleTypes
DROP TABLE Drivers
DROP TABLE DriverVehicleAppointments
DROP TABLE Shifts
DROP TABLE ShiftsDrivers
DROP TABLE CardLoadings
DROP TABLE DriverContacts
DROP TABLE Complaints
DROP TABLE Vehicles
DROP TABLE BusLines
DROP TABLE PassengerVehicles
DROP TABLE Departures
DROP TABLE Neighbourhoods
DROP TABLE BusStops
DROP TABLE Routes_
DROP TABLE Passengers
DROP TABLE CardTypes
