DROP TABLE Cities
DROP TABLE LoadingStations
DROP TABLE Municipalities
DROP TABLE VehicleRoute
DROP TABLE Card
DROP TABLE VehicleTypes
DROP TABLE Drivers
DROP TABLE AppointmentsDriverVehicle
DROP TABLE Shifts
DROP TABLE ShiftsDrivers
DROP TABLE CardLoading
DROP TABLE DriverContacts
DROP TABLE Complaint
DROP TABLE Vehicles
DROP TABLE BusLine
DROP TABLE PassengerVehicle
DROP TABLE Departure
DROP TABLE Neighbourhood
DROP TABLE BusStop
DROP TABLE Route
DROP TABLE Passenger
DROP TABLE CardType
